from matplotlib import pyplot as plt
plt.clf()

x, y1, y2, y3, y4, y5, y6, y7, y8, y9 = zip(
    *[tuple(
            map(
                int, line.strip().split()
            )
    ) for line in open("CollisionsInDifferentHashFunctions.txt").readlines()]
    )

plt.plot(x, y1)
plt.xlabel("Number of hashed objects")
plt.ylabel("Number of Collisions")
plt.savefig("Collisions in RS")
plt.clf()

plt.plot(x, y2)
plt.xlabel("Number of hashed objects")
plt.ylabel("Number of Collisions")
plt.savefig("Collisions in JS")
plt.clf()

plt.plot(x, y3)
plt.xlabel("Number of hashed objects")
plt.ylabel("Number of Collisions")
plt.savefig("Collisions in PJW")
plt.clf()

plt.plot(x, y4)
plt.xlabel("Number of hashed objects")
plt.ylabel("Number of Collisions")
plt.savefig("Collisions in ELF")
plt.clf()

plt.plot(x, y5)
plt.xlabel("Number of hashed objects")
plt.ylabel("Number of Collisions")
plt.savefig("Collisions in BKDR")
plt.clf()

plt.plot(x, y6)
plt.xlabel("Number of hashed objects")
plt.ylabel("Number of Collisions")
plt.savefig("Collisions in SDBM")
plt.clf()

plt.plot(x, y7)
plt.xlabel("Number of hashed objects")
plt.ylabel("Number of Collisions")
plt.savefig("Collisions in DJB")
plt.clf()

plt.plot(x, y8)
plt.xlabel("Number of hashed objects")
plt.ylabel("Number of Collisions")
plt.savefig("Collisions in DEK")
plt.clf()

plt.plot(x, y9)
plt.xlabel("Number of hashed objects")
plt.ylabel("Number of Collisions")
plt.savefig("Collisions in AP")
plt.clf()

plt.plot(x, y1, label="Collisions in RS")
plt.plot(x, y2, label="Collisions in JS")
plt.plot(x, y3, label="Collisions in PJW")
plt.plot(x, y4, label="Collisions in ELF")
plt.plot(x, y5, label="Collisions in BKDR")
plt.plot(x, y6, label="Collisions in SDBM")
plt.plot(x, y7, label="Collisions in DJB")
plt.plot(x, y8, label="Collisions in DEK")
plt.plot(x, y9, label="Collisions in AP")
plt.xlabel("Number of hashed objects")
plt.ylabel("Number of Collisions")
plt.legend()
plt.savefig("Collisions in different functions")
plt.clf()

plt.plot(x, y1, label="Collisions in RS")
plt.plot(x, y2, label="Collisions in JS")
plt.plot(x, y3, label="Collisions in PJW")
#plt.plot(x, y4, label="Collisions in ELF")
plt.plot(x, y5, label="Collisions in BKDR")
plt.plot(x, y6, label="Collisions in SDBM")
plt.plot(x, y7, label="Collisions in DJB")
plt.plot(x, y8, label="Collisions in DEK")
plt.plot(x, y9, label="Collisions in AP")
plt.xlabel("Number of hashed objects")
plt.ylabel("Number of Collisions")
plt.legend()
plt.savefig("Collisions in DifferentFunctionsWithoutELF")
plt.clf()

plt.plot(x, y1, label="Collisions in RS")
plt.plot(x, y2, label="Collisions in JS")
#plt.plot(x, y3, label="Collisions in PJW")
#plt.plot(x, y4, label="Collisions in ELF")
plt.plot(x, y5, label="Collisions in BKDR")
plt.plot(x, y6, label="Collisions in SDBM")
plt.plot(x, y7, label="Collisions in DJB")
plt.plot(x, y8, label="Collisions in DEK")
plt.plot(x, y9, label="Collisions in AP")
plt.xlabel("Number of hashed objects")
plt.ylabel("Number of Collisions")
plt.legend()
plt.savefig("Collisions in different functions without ELF and PJW")
plt.clf()